# This workflow will build a package using Gradle and then publish it to Maven Central when a release is created

name: Publish package to Maven Central

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set Up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '17'
        cache: 'gradle'
    - name: Change wrapper permissions
      run: chmod +x ./gradlew
          
    - name: Publish package
      run: ./gradlew :edge_to_edge_preview_lib:publishReleasePublicationToOSSRHRepository
      env:
        OSSRH_USER: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        OSSRH_PASSWORD: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
